spring.application.name=YouTube Tools
youtube.api.key=${YOUTUBE_API_KEY}
youtube.api.base.url=https://www.googleapis.com/youtube/v3
youtube.api.search.url=${youtube.api.base.url}/search
youtube.api.videos.url=${youtube.api.base.url}/videos

# Max number of related videos to fetch
youtube.api.max.related.videos=3

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/youtube_tools
spring.datasource.username=root
spring.datasource.password=Dk@8878545059



# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true